<?php

namespace AppBundle\Repository;

/**
 * ChatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatsRepository extends \Doctrine\ORM\EntityRepository
{
}
