<?php

namespace AppBundle\Repository;

/**
 * ModelesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelesRepository extends \Doctrine\ORM\EntityRepository
{
}
