<?php

namespace AppBundle\Repository;

/**
 * PartiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartiesRepository extends \Doctrine\ORM\EntityRepository
{
}
